spring:
  profiles.active: dev
  application.name: BananaMusic


logging:
  level.root: INFO

banana-music.openapi:
  dev-url: http://www.dev.bananamusicdb.es
  prod-url: http://www.prod.bananamusicdb.es

---
spring:
  profiles: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:bananamusicdb"
    driverClassName: org.h2.Driver
    username: banana
    password: platano
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server.port: 9090


---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bananamusicdb
    username: banana
    password: platano
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
  ssl:
    key-store: keystore2.p12
    key-store-password: abc123.
    keyStoreType: PKCS12
    keyAlias: tomcat

logging:
  level.root: WARN